### ISSUE TITLE
Sum of tensor goes to inf

### ISSUE THREAD

**Issue by rockerBOO** [MNoorFawi/curlora#1]
https://github.com/MNoorFawi/curlora/blob/aba39de3a2149ccfd3f5e833d52d26b4a2b43483/code/curlora.py#L19

It is possible for the sum `inverted_P.sum() ` to get high enough to be `inf`. But depends on the dtype, but on some 768x768 tensor it was hitting inf.

To solve I moved this to float/float32 after inverting.

```
    inverted_P = (1 / (probs + 0.001)).float()
```

And now is not hitting `inf`.

**Comment by MNoorFawi** [comment]
Hi @rockerBOO,
Thanks a lot for highlighting and solving the issue. Much appreciated. I have reflected your solution and will close the issue.
Thanks a lot.
